### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by tuupola**
This PR will allow the middleware to be installed with a PHP 8 compatible version of willdurand/negotiation thus making also the middleware itself PHP 8 compatible.

### CODE REVIEW

**Comment by gofabian** [comment]
Thanks for your Pull Request. Is there no breaking change between major versions 2 and 3?

**Comment by tuupola** [comment]
There is no CHANGELOG file but [comparing 2.3.1 and 3.0.0](https://github.com/willdurand/Negotiation/compare/v2.3.1...3.0.0) only thing seems to be renaming `Match` to `AcceptMatch`. I am using this in one old project which was upgraded to PHP-8 and have not encountered any problems.

**Comment by gofabian** [comment]
Would you mind to remove version 2. My plan is to support version 3 only.

Once #9 and #11 are fixed, we can merge this PR.

**Comment by tuupola** [comment]
Done.

**Pull request merged**
